### ISSUE TITLE
Need more documentation, I cannot implement

### ISSUE THREAD

**Issue by fafamonge** [mliebelt/PgnViewerJS-WP#3]
I've seen your good job about this and I'm very interesting to use it on my new website but I get a message in the browser console as following:

Local path: http://www.ajedrez.life/wp-content/plugins/pgnviewerjs-wp/
pgnvjs.js:3 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ pgnvjs.js:3
pgnvjs.js:7 Local path: http://www.ajedrez.life/wp-content/plugins/pgnviewerjs-wp/
pgnvjs.js?ver=4.7.5:5 Uncaught TypeError: $ is not a function
    at y (pgnvjs.js?ver=4.7.5:5)
    at A (pgnvjs.js?ver=4.7.5:5)
    at Object.vb.position (pgnvjs.js?ver=4.7.5:5)
    at E (pgnvjs.js?ver=4.7.5:8)
    at f (pgnvjs.js?ver=4.7.5:8)
    at HTMLElement.<anonymous> (pgnvjs.js?ver=4.7.5:8)
    at HTMLElement.dispatch (pgnvjs.js?ver=4.7.5:2)
    at HTMLElement.q.handle (pgnvjs.js?ver=4.7.5:2)

Can you help me with this? Thanks in advance.

**Comment by mliebelt** [comment]
I don't know when I will have the time to look at that. As you may have noticed, I have not updated the WordPress plugin based on my work on PgnViewerJS (also on GitHub) for months. I hope I can look at it in the next 2 weeks.

Thank's for getting in touch with me.

**Comment by mliebelt** [comment]
Checked it again with a local installation (in a virtual image) with Wordpress 4.7.5. It works like a charm for me, no additional installations of any kind, no plugins.  The error message looks like JQuery is not found or not installed. I cannot explain that effect.
